language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_install:
  - php /home/travis/.phpenv/versions/5.5.9/bin/composer.phar self-update

install:
  - php vendor/autoload.php

script:
  - phpunit -c tests.xml