language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer self-update
  - composer --prefer-source --dev install

install:
  - php vendor/autoload.php

script:
  - phpunit -c tests.xml